name: DAST - OWASP ZAP (Baseline)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  zap:
    name: ZAP Baseline Scan
    runs-on: ubuntu-latest

    # 🔑 Dá permissão para criar Issues (se quiser manter essa feature)
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Sobe um servidor simples servindo ./public na porta 8000
      - name: Start simple web server (port 8000)
        run: |
          python3 -m http.server 8000 --directory public &>/dev/null &
          sleep 3

      # Roda o ZAP Baseline
      - name: Run ZAP Baseline
        id: zap
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'http://localhost:8000'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Relatório DAST (ZAP Baseline)'
          allow_issue_writing: true       # define como false se NÃO quiser criar Issue
          fail_action: false              # 👈 não falha o job se houver alertas
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          artifact_name: 'zap_scan'

      # Faz upload dos relatórios sempre (HTML/JSON/MD)
      - name: Upload ZAP Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            report_html.html
            report_md.md
            report_json.json
