name: DAST - ZAP Baseline
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'  # semanal
jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & run PrivacidadeApi
        run: |
          dotnet build ./PrivacidadeApi/PrivacidadeApi.csproj -c Release
          dotnet run --project ./PrivacidadeApi/PrivacidadeApi.csproj --urls "http://0.0.0.0:5000" &
          echo $! > api.pid
          sleep 5

      - name: ZAP Baseline (AFTER - com correções)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:5000'
          cmd_options: '-a'
      - name: Coletar relatório
        run: |
          mkdir -p evidencias/zap
          cp report_html.html evidencias/zap/after.html || true
          cat zap.out > evidencias/zap/after.txt || true

      - name: Encerrar API
        run: kill $(cat api.pid) || true

      - uses: actions/upload-artifact@v4
        with:
          name: zap-after
          path: evidencias/zap
