name: DAST - ZAP Baseline
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # semanal
jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ secrets.ZAP_TARGET_URL }} # https://seu-endpoint
          rules_file_name: ''
          cmd_options: '-a'
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            zap.out
