- name: Find Web project
  id: web
  run: |
    set -e
    WEBPROJ=$(grep -rl '<Project Sdk="Microsoft.NET.Sdk.Web"' -- */*.csproj | head -n1 || true)
    if [ -z "$WEBPROJ" ]; then echo "Nenhum projeto Web (.NET) encontrado"; exit 1; fi
    echo "path=$WEBPROJ" >> $GITHUB_OUTPUT
    echo "Web project: $WEBPROJ"

- name: Build & run Web project
  run: |
    dotnet build "${{ steps.web.outputs.path }}" -c Release
    dotnet run --project "${{ steps.web.outputs.path }}" --urls "http://0.0.0.0:5000" & echo $! > api.pid
    for i in {1..30}; do
      if curl -sSf http://localhost:5000/ >/dev/null; then echo "API pronta!"; break; fi
      echo "Aguardando API..."; sleep 2
    done
