name: SAST - Semgrep (C#)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Regras de C# + (opcional) secrets
      - name: Semgrep scan (SARIF)
        run: >
          semgrep scan
          --config "p/csharp"
          --config "p/secrets"
          --sarif --output semgrep.sarif
          --severity INFO

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
