name: SCA - Dependencies
on: [push, pull_request]

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.0.x
            8.0.x
            7.0.x

      - name: Discover solution
        id: sln
        shell: bash
        run: |
          set -e
          SLN="$(ls -1 *.sln 2>/dev/null | head -n1 || true)"
          if [ -z "$SLN" ]; then
            # tenta achar em subpastas
            SLN="$(find . -maxdepth 3 -name '*.sln' | head -n1 || true)"
          fi
          if [ -z "$SLN" ]; then
            echo "Nenhuma .sln encontrada"; exit 1
          fi
          echo "sln=$SLN" >> "$GITHUB_OUTPUT"
          echo "Usando solução: $SLN"

      - name: Restore
        run: dotnet restore "${{ steps.sln.outputs.sln }}"

      - name: Find csproj files
        id: csproj
        run: |
          mapfile -t CSPROJS < <(find . -type f -name '*.csproj')
          if [ ${#CSPROJS[@]} -eq 0 ]; then
            echo "Nenhum .csproj encontrado"; exit 1
          fi
          printf "%s\n" "${CSPROJS[@]}" > evidencias/sca/csproj-list.txt
          echo "Encontrados:"
          cat evidencias/sca/csproj-list.txt

      - name: Vulnerable packages per project
        shell: bash
        run: |
          mkdir -p evidencias/sca
          > evidencias/sca/vulnerable.txt
          while IFS= read -r P; do
            echo "=== $P ===" | tee -a evidencias/sca/vulnerable.txt
            dotnet list "$P" package --vulnerable | tee -a evidencias/sca/vulnerable.txt || true
            echo "" >> evidencias/sca/vulnerable.txt
          done < evidencias/sca/csproj-list.txt

      - name: Gate High/Critical
        run: |
          if grep -Eiq 'High|Critical' evidencias/sca/vulnerable.txt; then
            echo "High/Critical vulnerabilities found"; exit 1; fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sca-artifacts
          path: evidencias/sca
